#!/bin/bash 
Help()
{
   # Display Help
   echo "wakeup laptop automatic when turn off v1"
   echo "========================================="
   echo ""
   echo "Syntax: wakeup <hh:mm> [option]"
   echo ""
   echo "options:"
   echo "--help		: Print this Help."
   echo "-s		: Set shutdown too in 70s"
   echo "-n		: Set wakeup time the next day."
   echo "-h [hours]	: Set wakeup time after [hours]."
   echo "-m [minutes]	: Set wakeup time after [minutes]."
}

isShutdown=0

if [ -z $1 ]
then
	timestamp="$(date '+%s' --date='tomorrow')"
else
	if [ $1 == "--help" ]
	then
		Help
		exit 0;
	fi

	clock="$1 today"
	while getopts "nh:m:s" option;
	  do
	    case $option in
	      n)
		clock="$1 next day"
		;;
	      h)
		clock="+$OPTARG hours"
		;;
	      m)
		clock="+$OPTARG minutes"
		;;
	      s)
		isShutdown=1
		;;
	    esac
	  done
	timestamp="$(date '+%s' --date="$clock")"
fi

#notify-send "run alarm on $(date --date=@$timestamp)"
rtcwake -l -m no --time $timestamp

if [ $isShutdown == 1 ]
then
	shutdown -h -t 10
fi
